---
title: "Answer Sheet - Midterm Exam"
author: "Conservation Biology"
date: "Fall 2024"
output: 
  pdf_document:
    toc: false
    number_sections: false
fontsize: 12pt
geometry: margin=1in
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead[L]{\textbf{Conservation Biology (Fall 2024)}}
  - \fancyhead[R]{Answer Sheet - Midterm Exam}
  - \fancyfoot[C]{\thepage}
params:
  local: "/Users/arich/Library/CloudStorage/GoogleDrive-aliciamrich@gmail.com/Other computers/My MacBook Pro/RStudioMacbook/GitRepos/teaching/"

---

```{r message=FALSE, warning=FALSE, include=FALSE}
source(paste0(params$local, "dependencies/setup.R"))
```

# Name: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
**October 23, 2024**\
**BIOL 4120 with Dr. Rich**

# Instructions

## Sections
This exam contains four sections: **True/False**, **Multiple Choice**, **Fill in the Blank**, and **Short Essay**. You must answer all questions from the first three sections, but you can choose any three of the Short Essay questions you wish to answer and ignore the others.

## Materials Allowed
You may reference any hard copy materials you brought with you (but not a classmate's materials). You may not use any electronic devices (computer, phone, tablet) during the exam.

## Submission
Use only this sheet or extra paper attached to write your answers. Do not write on your exam copy. You have until our normal end of class time to finish. ***Make sure you return both the exam and this answer sheet before you leave***

# Your Answers

## True/False
*1 pt each (15 points total)*\
\
Write TRUE or FALSE in each blank\
\
1. \_\_\_\_\_\_\_\_\_\_\_\
\
2. \_\_\_\_\_\_\_\_\_\_\_\
\
3. \_\_\_\_\_\_\_\_\_\_\_\
\
4. \_\_\_\_\_\_\_\_\_\_\_\
\
5. \_\_\_\_\_\_\_\_\_\_\_\
\
6. \_\_\_\_\_\_\_\_\_\_\_\
\
7. \_\_\_\_\_\_\_\_\_\_\_\
\
8. \_\_\_\_\_\_\_\_\_\_\_\
\
9. \_\_\_\_\_\_\_\_\_\_\_\
\
10. \_\_\_\_\_\_\_\_\_\_\_\
\
11. \_\_\_\_\_\_\_\_\_\_\_\
\
12. \_\_\_\_\_\_\_\_\_\_\_\
\
13. \_\_\_\_\_\_\_\_\_\_\_\
\
14. \_\_\_\_\_\_\_\_\_\_\_\
\
15. \_\_\_\_\_\_\_\_\_\_\_\
\
\

## Multiple Choice
*1 pts each (15 points total)*\
\
Write the letter of your answer (A, B, C, D, or E) in each blank.\
\
1. \_\_\_\_\_\_\_\_\_\_\_\
\
2. \_\_\_\_\_\_\_\_\_\_\_\
\
3. \_\_\_\_\_\_\_\_\_\_\_\
\
4. \_\_\_\_\_\_\_\_\_\_\_\
\
5. \_\_\_\_\_\_\_\_\_\_\_\
\
6. \_\_\_\_\_\_\_\_\_\_\_\
\
7. \_\_\_\_\_\_\_\_\_\_\_\
\
8. \_\_\_\_\_\_\_\_\_\_\_\
\
9. \_\_\_\_\_\_\_\_\_\_\_\
\
10. \_\_\_\_\_\_\_\_\_\_\_\
\
11. \_\_\_\_\_\_\_\_\_\_\_\
\
12. \_\_\_\_\_\_\_\_\_\_\_\
\
13. \_\_\_\_\_\_\_\_\_\_\_\
\
14. \_\_\_\_\_\_\_\_\_\_\_\
\
15. \_\_\_\_\_\_\_\_\_\_\_\
\
\

## Fill in the Blank
*2 pts each (20 points total)*\
\
Write your one or two-word answer in the blank.\
\
1. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
2. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
3. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
4. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
5. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
6. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
7. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
8. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
9. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
10. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\

## Short Essay
*5 pts each (15 points total)*\
\
You can choose any three of the Short Essay questions you wish to answer and ignore the others. I will grade the first three answers that appear, so do not try to answer more than that.\
\
Write your response in the space below. Your answers should not be longer than a short paragraph, but if you do need extra space you can attach additional paper to this answer sheet.\
\
***1. Question you are answering:***\_\_\_\_\_\_\_\_\
**Your response:**\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\
***2. Question you are answering:***\_\_\_\_\_\_\_\_\
**Your response:**\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\
***3. Question you are answering:***\_\_\_\_\_\_\_\_\
**Your response:**\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
\
\

